{% set name = "udocker" %}
{% set version = "1.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb728be0ac8e0329e0c0ee6b1a82dcb1241f464c37705bbffad8cfb2c40c9996
  #git_url: https://github.com/indigo-dc/udocker.git
  patches:
    - setup.py.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - __linux

test:
  imports:
    - udocker
  requires:
    - pip
    - pytest-runner
    - pycurl
  source_files:
    - tests
  commands:
    - pip check
    - pytest
    - udocker version
    - udocker images
    - udocker ps

about:
  home: https://github.com/indigo-dc/udocker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: udocker is a basic user tool to execute simple docker containers in user space without requiring root privileges.

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - mariojmdavid
